### ISSUE TITLE
switch to HFS+ for release dmg

### ISSUE THREAD

**Issue by m000** [everettjf/MachOExplorer#22]
It would be nice to switch release dmgs to HFS+.

The release dmg seems to contain an APFS partition. This prevents MachOExplorer from being installed on older versions of MacOS. The app itself does not seem limited to newer versions of MacOS.

**Comment by everettjf** [comment]
Thanks, I will fix it in two weeks along with some other bugs.

**Comment by follower** [comment]
I can confirm that https://github.com/everettjf/MachOExplorer/releases/download/v1.0/MachOExplorer.dmg is now HFS+ format.

Note however that the minimum OS version to run the app is 10.11 (which I assume is due at least in part to use of Qt 5.10).

**Comment by everettjf** [comment]
@follower Thanks for your confirmation. 
Yes, it is based on Qt5.10.
